/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2022-08-17 07:40:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.includes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class allNav_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1653831082294L));
    _jspx_dependants.put("jar:file:/C:/Users/kkao4/Desktop/RPA-project/jeahyun/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProjectRPA/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/CSS/nav.css\">\r\n");
      out.write("<!-- <style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("         margin: 0;\r\n");
      out.write("         padding: 0;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     body {\r\n");
      out.write("         width: 100%; height: 100%; background:#333\r\n");
      out.write("         \r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     header{\r\n");
      out.write("     width: 1500px; height: 90px; margin: auto; display: block; \r\n");
      out.write("     /* background-color: aqua; */\r\n");
      out.write("     \r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #Logo{\r\n");
      out.write("     width:130px; height: 76px; margin:25px 10px 10px 10px; float: left; background-color:#b9e4b9;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #nav{\r\n");
      out.write("         width: 900px;height: 30px;margin: 50px 0 0 0;float: left;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #menu1{\r\n");
      out.write("         \r\n");
      out.write("         height: 50px;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #menu1 ul li {\r\n");
      out.write("         list-style: none; font-family: \"Arial\"; font-weight: bold; margin:0 auto;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #menu1 .main .title {\r\n");
      out.write("         float: left; padding: 0 30px;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #menu1 .main .title>a{\r\n");
      out.write("         text-decoration: none; color: rgb(236, 227, 227); padding: 9px;\r\n");
      out.write("         display: inline-block;\r\n");
      out.write("         border: 1px solid;\r\n");
      out.write("         border-radius: 10%;\r\n");
      out.write("         background: rgb(113, 109, 109);\r\n");
      out.write("         cursor: pointer;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #menu1 .main .title>a:hover{color: rgb(92, 233, 92);}\r\n");
      out.write("\r\n");
      out.write("     #menu1 .main .subtitle {\r\n");
      out.write("         width: 70px;\r\n");
      out.write("         height: 50px;\r\n");
      out.write("         line-height: 50px;\r\n");
      out.write("         text-align: center;\r\n");
      out.write("         background: rgb(113, 109, 109);\r\n");
      out.write("         padding: 0 30px;\r\n");
      out.write("         position: relative;\r\n");
      out.write("         border: 1px;\r\n");
      out.write("         border-radius: 5%;\r\n");
      out.write("         list-style: none;\r\n");
      out.write("         text-decoration: none; color: rgb(236, 227, 227); padding: 8px;\r\n");
      out.write("         cursor: pointer;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #menu1 .main>li:hover .sub {\r\n");
      out.write("         display: block;\r\n");
      out.write("     }\r\n");
      out.write("     \r\n");
      out.write("     #menu1 .main>li a {\r\n");
      out.write("         display: block;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #menu1 .main .subtitle a:hover {\r\n");
      out.write("         color: #fff;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #menu1 .main .sub {\r\n");
      out.write("         left: 0 1;\r\n");
      out.write("         position: absolute;\r\n");
      out.write("         display: none;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #menu1 .main .sub li {\r\n");
      out.write("         background: #f5eff5;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #menu1 .main .sub li a:hover {\r\n");
      out.write("         background: #b9e4b9;\r\n");
      out.write("         \r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #right_nav {\r\n");
      out.write("         width: 400px;\r\n");
      out.write("         height: 50px;\r\n");
      out.write("         margin: 50px 0 0 0; float: right;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #right_nav .right {\r\n");
      out.write("         font-family: \"Arial\"; font-weight: bold; list-style: none; margin:0 auto;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #right_nav .right li {\r\n");
      out.write("         float: left; padding: 0 60px;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #right_nav .right li a {\r\n");
      out.write("         text-decoration: none; color: rgb(236, 227, 227); padding: 9px;\r\n");
      out.write("         display: inline-block;\r\n");
      out.write("         border: 1px solid;\r\n");
      out.write("         border-radius: 10%;\r\n");
      out.write("         background: rgb(113, 109, 109);\r\n");
      out.write("         cursor: pointer;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #right_nav .right li a:hover {\r\n");
      out.write("         color: rgb(92, 233, 92);\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #side{\r\n");
      out.write("     display: block;\r\n");
      out.write("     list-style: none;\r\n");
      out.write("     margin-top: 20%;\r\n");
      out.write("     margin-left: 30PX;\r\n");
      out.write("     width: 150px;\r\n");
      out.write("     height: 200PX;\r\n");
      out.write("     position:fixed;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #side>li{\r\n");
      out.write("         padding: 10px;\r\n");
      out.write("         float: left;\r\n");
      out.write("         font-family: \"Arial\";font-weight: bold;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #side>li>a{\r\n");
      out.write("         text-decoration: none; color: rgb(236, 227, 227); padding: 9px;\r\n");
      out.write("         display: inline-block;\r\n");
      out.write("         border: 1px solid;\r\n");
      out.write("         border-radius: 10%;\r\n");
      out.write("         background: rgb(113, 109, 109);\r\n");
      out.write("         cursor: pointer;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #side>li>a:hover{\r\n");
      out.write("         color: rgb(92, 233, 92);  \r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #rightbar{\r\n");
      out.write("         list-style: none;\r\n");
      out.write("         float: right;\r\n");
      out.write("         position: fixed;\r\n");
      out.write("         height: 50px;\r\n");
      out.write("         text-align: right;\r\n");
      out.write("         width: 120px;\r\n");
      out.write("         right: 20px;\r\n");
      out.write("         display: block;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #rightbar>li{\r\n");
      out.write("         padding: 10px;\r\n");
      out.write("         float: left;\r\n");
      out.write("         font-family: \"Arial\";font-weight: bold;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #rightbar>li>a{\r\n");
      out.write("         text-decoration: none; color: rgb(236, 227, 227); padding: 9px;\r\n");
      out.write("         display: inline-block;\r\n");
      out.write("         border: 1px solid;\r\n");
      out.write("         border-radius: 10%;\r\n");
      out.write("         background: rgb(113, 109, 109);\r\n");
      out.write("         cursor: pointer;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #rightbar>li>a:hover{\r\n");
      out.write("         color: rgb(92, 233, 92);\r\n");
      out.write("     }\r\n");
      out.write("</style> -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("        <div id=\"Logo\">\r\n");
      out.write("            <img src=\"#\" >\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<nav id=\"nav\">\r\n");
      out.write("    <div id=\"menu1\">\r\n");
      out.write("          <ul class=\"main\">\r\n");
      out.write("            <li class=\"title\"><a href=\"#\">시설소개</a>\r\n");
      out.write("                  <ul class=\"sub\">\r\n");
      out.write("                    <li class=\"subtitle\"><a href=\"#\">시험메뉴</a></li>\r\n");
      out.write("                    <li class=\"subtitle\"><a href=\"#\">시험메뉴</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"title\"><a href=\"#\">강사소개</a>\r\n");
      out.write("                <ul class=\"sub\">\r\n");
      out.write("                  <li class=\"subtitle\"><a href=\"#\">시험메뉴</a></li>\r\n");
      out.write("                  <li class=\"subtitle\"><a href=\"#\">시험메뉴</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li class=\"title\"><a href=\"#\">PT예약</a>\r\n");
      out.write("                <ul class=\"sub\">\r\n");
      out.write("                  <li class=\"subtitle\"><a href=\"#\">시험메뉴</a></li>\r\n");
      out.write("                  <li class=\"subtitle\"><a href=\"#\">시험메뉴</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li class=\"title\"><a href=\"#\">이용권</a>\r\n");
      out.write("                <ul class=\"sub\">\r\n");
      out.write("                  <li class=\"subtitle\"><a href=\"#\">시험메뉴</a></li>\r\n");
      out.write("                  <li class=\"subtitle\"><a href=\"#\">시험메뉴</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li class=\"title\"><a href=\"#\">상 품</a>\r\n");
      out.write("                <ul class=\"sub\">\r\n");
      out.write("                  <li class=\"subtitle\"><a href=\"#\">시험메뉴</a></li>\r\n");
      out.write("                  <li class=\"subtitle\"><a href=\"#\">시험메뉴</a></li>\r\n");
      out.write("                  <li class=\"subtitle\"><a href=\"#\">시험메뉴</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li class=\"title\"><a href=\"#\">커뮤니티</a>\r\n");
      out.write("                <ul class=\"sub\">\r\n");
      out.write("                  <li class=\"subtitle\"><a href=\"#\">시험메뉴</a></li>\r\n");
      out.write("                  <li class=\"subtitle\"><a href=\"#\">시험메뉴</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<nav id=\"right_nav\">\r\n");
      out.write("    <div class=\"right_menu\">\r\n");
      out.write("        <ul class=\"right\">\r\n");
      out.write("            <li><a href=\"#\">전체보기</a></li>\r\n");
      out.write("            <li>");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("            <li>");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("            <li>");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("</header>\r\n");
      out.write("<hr width=\"1500px\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"side\">\r\n");
      out.write("	    <li><a href=\"#\">오시는길</a></li>\r\n");
      out.write("	    <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("	    <li><a href=\"#\">고객센터</a></li>\r\n");
      out.write("	    <li><a href=\"#\">1:1 문 의</a></li>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"rightbar\">\r\n");
      out.write("		<li><a href=\"#\">장바구니</a></li>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/includes/allNav.jsp(249,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<a href=\"/user/login\">로그인</a>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/includes/allNav.jsp(250,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<a href=\"/user/logout\">로그아웃</a>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/includes/allNav.jsp(251,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('<');
          out.write('p');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 안녕하세요.</p>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
